In [27]:
import pandas as pd

def _get_opposing_pitcher(df):
    
    wins = df[(df['W/L'] == 'W') | (df['W/L'] == 'W-wo')]
    loss = df[(df['W/L'] == 'L') | (df['W/L'] == 'L-wo')]
    
    wins['opp_pitcher'] = wins['Loss']
    loss['opp_pitcher'] = loss['Win']
    
    new = pd.concat([wins,loss])
    return new

#Append above column to hitter data
#Will need once we scrape more hitter data
def append_opposing_pitcher(hitter_data,schedule_df):
    #Reformat hitter dates
    hitter_data['Game Date'] = hitter_data['Game Date'].apply(lambda x: x.replace('\\r\\n','').strip())
    hitter_data['Game Date'] = pd.to_datetime(hitter_data['Game Date'],format="%m/%d/%Y",errors='coerce')
    schedule_df['Date'] = pd.to_datetime(schedule_df['Date'],format="%m/%d/%Y",errors='coerce')
    
    df1 = pd.merge(hitter_data,schedule_df[['Date','Opp','opp_pitcher','Gm#','Team']],how='left',
                   left_on=['Team','Game Date'],right_on=['Team','Date'])
    df1.dropna(inplace=True)
    return df1

In [28]:
import os

In [29]:
from settings import *

In [30]:
all_dfs = []
for f in os.listdir('_data/schedules/original_2017'):
    print 'Working on %s...' %f
    df = pd.read_csv('_data/schedules/original_2017' +'/'+ f)
    df1 = _get_opposing_pitcher(df)
    
    sch = df1[['Date','Opp','opp_pitcher','Gm#']]
    sch['Team'] = baseballRef_to_baseballMus.get(f)
    
    
    all_dfs.append(sch)
    #df1.to_csv(TRANS_SCHEDULES + '\\'+ f.replace('.txt','.csv'))

Working on ARI...
Working on ATL...

/Users/davidherook/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/davidherook/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Working on BAL...
Working on BOS...
Working on CHC...
Working on CHW...
Working on CIN...
Working on CLE...
Working on COL...
Working on DET...
Working on HOU...
Working on KCR...
Working on LAA...
Working on LAD...
Working on MIA...
Working on MIL...
Working on MIN...
Working on NYM...
Working on NYY...
Working on OAK...
Working on PHI...
Working on PIT...
Working on SDP...
Working on SEA...
Working on SFG...
Working on STL...
Working on TBR...
Working on TEX...
Working on TOR...
Working on WSN...

In [31]:
all_dfs1 = pd.concat(all_dfs)[['Opp','opp_pitcher','Gm#','Team','Date']]

In [33]:
all_dfs1['Team'].value_counts()

PHI    162
SDN    162
MIN    162
MIA    162
BOS    162
OAK    162
NYN    162
NYA    162
PIT    162
CHA    162
CHN    162
LAN    162
LAA    162
SFN    162
DET    162
KCA    162
TBA    162
ATL    162
COL    162
TEX    162
SEA    162
CLE    162
TOR    162
WSH    162
CIN    162
BAL    162
SLN    162
HOU    162
ARI    162
MIL    162
Name: Team, dtype: int64

In [35]:
all_dfs1

     Opp opp_pitcher  Gm# Team               Date
0    SFG    Melancon    1  ARI       Sunday Apr 2
2    SFG       Moore    3  ARI    Wednesday Apr 5
3    SFG  Samardzija    4  ARI     Thursday Apr 6
4    CLE      Tomlin    5  ARI       Friday Apr 7
5    CLE       Bauer    6  ARI     Saturday Apr 8
6    CLE      Kluber    7  ARI       Sunday Apr 9
8    SFG  Samardzija    9  ARI     Tuesday Apr 11
12   LAD        Hill   13  ARI      Sunday Apr 16
13   LAD     Hatcher   14  ARI      Monday Apr 17
14   SDP      Cosart   15  ARI     Tuesday Apr 18
17   LAD   Stripling   18  ARI      Friday Apr 21
18   LAD       Maeda   19  ARI    Saturday Apr 22
20   SDP      Chacin   21  ARI      Monday Apr 24
21   SDP     Richard   22  ARI     Tuesday Apr 25
23   SDP      Weaver   24  ARI    Thursday Apr 27
26   COL       Lyles   27  ARI      Sunday Apr 30
27   WSN       Roark   28  ARI      Tuesday May 2
30   COL     Marquez   31  ARI       Friday May 5
34   DET        Boyd   35  ARI   Wednesday May 10
35   PIT        Cole   36  ARI    Thursday May 11
36   PIT     Glasnow   37  ARI      Friday May 12
39   NYM      Robles   40  ARI      Monday May 15
40   NYM      Milone   41  ARI     Tuesday May 16
41   NYM     Montero   42  ARI   Wednesday May 17
42   SDP      Weaver   43  ARI      Friday May 19
43   SDP     Perdomo   44  ARI    Saturday May 20
45   CHW    Gonzalez   46  ARI      Monday May 22
46   CHW       Covey   47  ARI     Tuesday May 23
47   CHW    Quintana   48  ARI   Wednesday May 24
48   MIL      Davies   49  ARI    Thursday May 25
..   ...         ...  ...  ...                ...
86   ATL     Teheran   87  WSH     Saturday Jul 8
93   LAA       Meyer   94  WSH   Wednesday Jul 19
94   ARI      Rodney   95  WSH      Friday Jul 21
97   MIL      Davies   98  WSH     Tuesday Jul 25
100  COL     Marquez  101  WSH    Saturday Jul 29
101  COL    Freeland  102  WSH  Sunday Jul 30 (1)
104  MIA     McGowan  105  WSH      Tuesday Aug 1
105  MIA      Worley  106  WSH    Wednesday Aug 2
107  CHC      Lackey  108  WSH     Saturday Aug 5
110  MIA      Worley  111  WSH      Tuesday Aug 8
114  SFG    Stratton  115  WSH  Sunday Aug 13 (1)
117  LAA     Nolasco  118  WSH   Wednesday Aug 16
120  SDP        Wood  121  WSH    Saturday Aug 19
123  HOU       Fiers  124  WSH   Wednesday Aug 23
125  NYM      deGrom  126  WSH      Friday Aug 25
127  NYM     Blevins  128  WSH  Sunday Aug 27 (1)
132  MIL      Davies  133  WSH    Thursday Aug 31
133  MIL      Nelson  134  WSH       Friday Sep 1
135  MIL    Jeffress  136  WSH       Sunday Sep 3
141  PHI      Leiter  142  WSH     Saturday Sep 9
143  ATL     Teheran  144  WSH     Tuesday Sep 12
144  ATL      Gohara  145  WSH   Wednesday Sep 13
146  LAD        Wood  147  WSH      Friday Sep 15
147  LAD        Hill  148  WSH    Saturday Sep 16
151  ATL      Dickey  152  WSH    Thursday Sep 21
152  NYM    Bradford  153  WSH      Friday Sep 22
156  PHI    Thompson  157  WSH     Tuesday Sep 26
157  PHI        Rios  158  WSH   Wednesday Sep 27
160  PIT      Kontos  161  WSH    Saturday Sep 30
161  PIT     Sanchez  162  WSH       Sunday Oct 1

[4860 rows x 5 columns]

In [60]:
all_dfs1['Date'] = pd.to_datetime(all_dfs1['Date'].apply(lambda x: ' '.join(x.split()[1:] ) + ' 2017'),
               errors='coerce',
               format='%b %d %Y')

In [66]:
def convert_date(x):
    try:
        return x.strftime('%m/%d/%Y')
    except:
        return x

In [68]:
all_dfs1['Date'] = all_dfs1['Date'].apply(lambda x: convert_date(x))

In [69]:
all_dfs1.to_csv('_data/schedules/_ALL_SCHEDULES_2017.csv')